### ISSUE TITLE
Python syntax highlighting errors

### ISSUE THREAD

**Issue by RenatoUtsch** [sheerun/vim-polyglot#209] opened 2017-05-06 16:38 UTC
I don't know why #167 was closed, because it is still buggy.

vim-polyglot's syntax highlighting stops highlighting for example 'None', or 'super', 'zip', 'enumerate', etc (words that are important in python but not keywords).

For now I need to disable vim-polyglot for Python, because the default syntax highlighting works correctly.

Is it possible to fix this in vim-polyglot?

**Comment by sheerun** [comment] 2017-05-07 09:12
I'd rather not fix anything, but use a different plugin. Which one should I use to fix your issue?

**Comment by RenatoUtsch** [comment] 2017-05-07 12:11
If you take a look at vim's source, you'll notice that the default python.vim was completely refactored, and is newer than all other Python syntax plugins I could find on the web:
https://github.com/vim/vim/blob/master/runtime/syntax/python.vim
https://github.com/vim/vim/blob/master/runtime/ftplugin/python.vim

So for newer vim/neovim versions, the default syntax plugin is actually very good. It fixes many highlighting problems and has good python 2/3 support.

What might be a good idea is to ship these newer default python plugins to people that have older vim/neovim versions, instead of using a not mantained and outdated plugin that doesn't support python 3 correctly.

**Comment by sheerun** [comment] 2017-05-17 09:11
@RenatoUtsch Maybe you want to extract is as github repository, so I can include it here?

**Comment by renstrom** [comment] 2017-05-30 08:32
https://github.com/vim-python/python-syntax together with `let g:python_highlight_all = 1` is probably the most complete and up-to-date.

**Comment by RenatoUtsch** [comment] 2017-05-30 09:03
+1

**Comment by Grelek** [comment] 2017-06-15 22:56
+1, this bothers me too

**Comment by dajuno** [comment] 2017-07-05 20:29
How about indenting though? Default config is a mess.
Maybe this: https://github.com/Vimjas/vim-python-pep8-indent

**Comment by Julian** [comment] 2017-09-30 14:48
I haven't taken time to investigate, but both of the options mentioned above seem to have regressions compared to what's here now.

```
def foo():
    bar(
        bla=1,
        baz=2,
        spam=3,
    )
```
seems to have one of them align the closing paren with the end of args, instead of leaving it where it is, and the main thing that brought me here:

```
def foo():
    bar(
        something="""
            <some>
                 <xml>
                  stuff
                 </xml>
             </some>
        """
     )
```
has everything here ruin the indentation in the string literal.

**Comment by sheerun** [comment] 2017-12-30 10:55
I've changes python syntax providers to:
- [vim-python/python-syntax](https://github.com/vim-python/python-syntax)
- [aliev/vim-compiler-python](https://github.com/aliev/vim-compiler-python)
- [Vimjas/vim-python-pep8-indent](https://github.com/Vimjas/vim-python-pep8-indent)

with `let g:python_highlight_all = 1`

If you find issues with your syntax highlighting, indentation or compiler support, please contribute to these repositories, vim-polyglot will fetch these changes periodically.

**Closed** 2017-12-30 10:55 UTC
Labels: Feedback required

**Comment by LnL7** [comment] 2018-07-26 18:30
I'm noticing the similar problems as #321, not sure if this is since https://github.com/sheerun/vim-polyglot/commit/17ad302c54063be1871c7f82d75b77e7c595e10c or a recent upstream issue but removing `share/vim-plugins/vim-polyglot/indent/python.vim` makes it much better.
However https://github.com/vim-python/python-syntax is also unusable for larger files without and it drops highlighting when jumping to the end of files. Using `let g:python_slow_sync = 0` makes this better and even then it's still a noticeably slower.

I feel like polyglot shouldn't override any of the builtin syntaxes provided by vim itself, and provide lightweight implementations for missing languages.
