### ISSUE TITLE
CoffeeScript filetype detection not working on last update

### ISSUE THREAD

**Issue by iovis9** [sheerun/vim-polyglot#262] opened 2018-01-09 15:36 UTC
Setting the filetype manually renders the syntax correctly. It was working properly till I updated yesterday.

How can I help you debug this?

**Comment by lasseebert** [comment] 2018-01-10 10:27
I'm seeing the same thing with `.exs` files in Elixir. `.ex` files works as expected. I just updated vim-polyglot and it was working before.

**Comment by lasseebert** [comment] 2018-01-10 10:33
Perhaps related to this commit: https://github.com/sheerun/vim-polyglot/commit/cef5e2d93100c4b765d276914658eab75906f4c9

It works on 3.3.0 and breaks on 3.3.1

**Comment by sheerun** [comment] 2018-01-10 22:55
bfc6ed9 should fix detecting by file extension, but I need a volunteer to fix detecting by first line of file (i.e. do single getline(1) and then match or result).

**Comment by lasseebert** [comment] 2018-01-11 07:26
I can confirm that the latest master fixes the issue for me. Thanks :+1:

I'm affraid I can't be of much help implementing the getline(1)-thing, since I can't VimScript.

**Comment by iovis9** [comment] 2018-01-11 13:58
Confirmed working now

**Comment by sheerun** [comment] 2018-02-06 03:26
Moved issue about detecting filetype given first line to: #274 

Closing this one, thank you for reporting :)

**Closed by sheerun** 2018-02-06 03:26 UTC
