### ISSUE TITLE
set noswapfile

### ISSUE THREAD

**Issue by magras** [sheerun/vim-polyglot#638] opened 2020-11-26 22:20 UTC
**Describe the bug:**
In commit 739102e06df4fe5bca752d1163b954603912bc98 swap files had been disabled. I don't think that silently disabling swap files by default is a good idea and I learned about it the hard way.

**To Reproduce:**
```
:set swapfile?
noswapfile
```

**Workaround:**
```
let g:polyglot_disabled = ['sensible']
```

**Comment by sheerun** [comment] 2020-11-27 15:05
what happened?

**Comment by magras** [comment] 2020-11-27 17:39
Short power outage caused unexpected shutdown and without swap file I lost unsaved changes.

**Comment by jgb** [comment] 2020-12-14 11:04
Allow me to voice my concern as well. I don't think it's a good idea to change one of vim's defaults. I got bitten by this as well, and managed to trace the culprit to be vim-polyglot.
What does this have to do with sensible anyway, sensible doesn't turn off swapfiles?

**Comment by beauwilliams** [comment] 2020-12-18 02:47
Yes, please do not touch swap file settings. This caused me a couple of headaches today trying to figure out what happened to them..

**Comment by WhyNotHugo** [comment] 2020-12-27 10:18
I've had data loss a few times, and was debugging nvim to figure out when this regression had happened.

It took me half a day to figure out that polyglot has silently introduced this regression. I think that a library that provides syntax highlighting should disable unrelated nvim features (and there's not even a warning in the README!). Here's one of the scenarios where it has several times led to data loss:

### Steps to reproduce

1. Open a file in one nvim instance. Make some changes.
2. Open the same file on another nvim instance. Make some changes, save and exit.

### Expected behaviour

When opening the second instance neovim warns that the file is already open.

### Actual behaviour / regression

There's no indication that the file is already open. After closing the second instance and later landing back on the first instance, I now have one in-memory file and one on-disk file with divergent changes.

While it's possible to work around this by manually saving with another filename and using `vimdiff`, that's a lot of work to be done.

This sort of under-the-hood changes are wildly out-of-scope for a syntax-highlighting plugin.

---

There's also many other scenarios where this leads to data loss. Accidentally closing the terminal where `nvim`is running also immediately destroys any changes. Running out of battery on a laptop does too.

**Comment by sheerun** [comment] 2020-12-29 23:58
@WhyNotHugo As for first dataloss scenario, vim-polyglot currently is configured as so to display a warning if file is saved somewhere else. Here's screencast https://v.usetapes.com/Y5SRU9q9Ni

Recent commit https://github.com/sheerun/vim-polyglot/commit/44e79fc935004c2e67fc39a77266d0f06e29d920 should improve this even more by issuing this warning immediately after window gains focus, instead of keypress

As for other dataloss scenarios, I agree this is not perfect. This can be fixed by enabling swapfiles but making sure each session gets different swapfile name (afaik this, or no swapfiles, it is needed for `autoread` to properly work, and to allow editing same file in multiple windows without annoying warnings). I'll try to implement it.

**Comment by roachsinai** [comment] 2020-12-30 05:12
Hi @sheerun , my cursor is block before this update. After this update, the cursor in insert mode is vertical bar.

So, why this issue involved cursor setting? Is there a way to let it back...

**Comment by roachsinai** [comment] 2020-12-30 05:31
By the way you said:

> Do not mention vim-sensible, as only tiny part of it is included

at commit https://github.com/sheerun/vim-polyglot/commit/47dcae9131ac32cabf92f49093f044732a412450

Does it mean, we can remove setting: `let g:polyglot_disabled = ['sensible']`?

**Comment by sheerun** [comment] 2020-12-30 07:40
@roachsinai Okay, I've reverted this change. Still, there should be a warning after user starts typing in non-saved window, just like on screencast. You can remove `let g:polyglot_disabled = ['sensible']` if you agree with defaults set by vim-polyglot.

**Comment by roachsinai** [comment] 2020-12-30 08:00
@sheerun Thanks for quick reply, appreciated it so much!

**Comment by WhyNotHugo** [comment] 2020-12-30 08:34
@sheerun I guess this screencast kinda explains what you're trying to do by disabling swapfiles, but that really seems like a huge feature creep for vim-polyglot.

I installed this plugin to get syntax highlighting for different filestypes -- and this functionality seems to be entirely unrelated, and completely change the way Vim works (in ways that are, personally, entirely undesireable for me).

Also, it seems that by the time that a warning is shown, it's too late, a conflict is already there. The options are to drop change or reload file, but one has screwed up.

And this is just one of the problematic scenarios.

Could you please consider implementing this all this functionality in a separate plugin? Personally, I'm using `vim-polyglot` for its highlighting feature (the README advertises Vim as simply this). If this plugin is going to slowly convert Vim into a completely different tool, I'd appreciate some clarification, since this is definitely not what I'm looking for.

Just to be clear, I understand that it's your plugin and it's your prerrogative to bundle as many unrelated features as you like into it, but if vim-polyglot is going to become a completely-change-Vim kind of thing, I'd appreciate just being transparent about it so we make an informed decision of whether it's what we're looking for or not.

**Comment by jgb** [comment] 2020-12-30 08:55
I used to explicitly install about 5 syntax and indent files. A while ago I replaced that approach with vim-polyglot. However this incident and the way it's being handled makes me consider ditching polyglot and going back to my old approach. 
I want polyglot to provide syntax and indent support. No more. No less. If I want vim-sensible, I'll install it. And polyglot should definitely not change any vim settings behind my back!

**Comment by sheerun** [comment] 2020-12-30 08:59
I've enabled again swapfiles, so `:recover` should always work. Just disabling the warning message so `autoread` also works

**Closed** 2020-12-30 08:58 UTC

**Comment by roachsinai** [comment] 2020-12-30 09:08
@jgb just calm dowm, bro. @WhyNotHugo I can't agree more with your points. @sheerun Thanks for this wonderful plugin and I think a seperate plugin is better choice for other functionality.

**Comment by sheerun** [comment] 2020-12-30 09:16
No swapfiles was not intended "feature". The only reason it was disabled was to allow `autoread` to work (so editing in multiple windows or vim instances is possible, just like with normal editors). Now that I've found the way to make it work with swapfiles, I can enable them again. Thank you for the feedback, I hope it's acceptable now. If not, please open another issue

**Comment by roachsinai** [comment] 2020-12-30 09:44
So for people not use `autoread` and need `swapfile` just set `let g:polyglot_disabled = ['sensible']` as it's no business about syntax, highlight, right?

**Comment by sheerun** [comment] 2020-12-30 09:53
If someone just wants swapfile, nothing needs to be done, as polyglot doesn't touch this setting now. If someone doesn't want `autoread`, well then `set noautoread` or `let g:polyglot_disabled = ['sensible']` is still needed

**Comment by roachsinai** [comment] 2020-12-30 10:08
It not a good experience for people don't need it, we comment here and disable things about `sensible`.

But I must say this plugin did help me a lot on syntax and highlight.

**Comment by sheerun** [comment] 2020-12-30 10:14
Why is `autoread` not a good experience?

**Comment by roachsinai** [comment] 2020-12-30 10:21
> Why is `autoread` not a good experience?

Not saying `autoread` is not a good experience, but some setting from `sensible` adding to this plugin for people using swapfile.

For `autoread` sometimes a external program will change  a file in my current vim window, but I just let it just change, then I use vim to overwrite it to clear the change. So I think this time `autoread` is harmful for me.

**Comment by sheerun** [comment] 2020-12-30 10:45
@roachsinai Changes applied by external program are part of undo history of original window, so it's enough to type `u` to undo this change. Additionaly `autoread` saves you from situation where you open same file in two windows, make changes in one window, then use other window to do different changes, and by mistake override changes made in the first.

**Comment by sheerun** [comment] 2020-12-30 10:45
Here's screencast showing it: https://v.usetapes.com/2LM9XBCzS6

**Comment by WhyNotHugo** [comment] 2020-12-30 11:20
> Why is `autoread` not a good experience?

I don't want `vim` to try to replace my current buffer automatically with something else unless I tell it to. While I understand that others can expect different behaviours from their editors, I personally dislike "magic' happening.

If I've two editor with the same file, I likely have a reason for that (e.g.: I switched to another branch, and I'm doing a quick edit before going back, for example). My workflow is always open>edit>save. `autoread` sounds like it would required my workflow to be though of as a directed graph with external events changing my buffers, which is just too much for me to keep in my head.

**Comment by sheerun** [comment] 2020-12-30 11:56
> I switched to another branch, and I'm doing a quick edit before going back, for example

But if you don't go back, then you need to remember to refresh all buffers manually, otherwise you again get data loss.

If you don't save first buffer and switch branch, the behavior is show warning if external changes, as shown on screencast: https://v.usetapes.com/e1MUn3PxJP so no "magic" should happen for you in this case

If you save and commit, then switch branch before going back, all changes are within git history, and `autoread` will read them after you switch back to first branch. `autoread` makes all vim windows synchronized, so you don't need to remember which you've refreshed and which one you not. It's really easy to override your changes without `autoread`.

If file is saved before you change branch, you often can't change branch without stashing changes (you get `Please commit your changes or stash them before you switch branches` error message). In such case again all changes are again within git history and will be restored automatically in all vim windows by `autoread`.

Could you please describe workflow that makes unexpected "magic" changes? It's hard to me to imagine such case
