### ISSUE TITLE
Recent commit broke some TSX highlight groups

### ISSUE THREAD

**Issue by bignimbus** [sheerun/vim-polyglot#551] opened 2020-09-18 16:28 UTC
Thank you for this amazing plugin!  Here is the issue:

**Does this bug happen when you install plugin without vim-polyglot?**

No

**Describe the bug:**

When I pull the latest `master` branch, syntax highlighting for TSX is different/worse (IMO).  When I target the commit right before https://github.com/sheerun/vim-polyglot/commit/8dd0474feb60a4b9f50ee2b8decead0146623966, my issue is fixed.

**To Reproduce:**
To establish a baseline, open a TSX file with revision https://github.com/sheerun/vim-polyglot/commit/e166f741ef054ea990aa6d1af85b97ceb82171bb checked out.

Then, checkout any subsequent revision and open the same TSX file.  The highlights are visibly different.

**Comment by sheerun** [comment] 2020-09-19 10:33
For me it looks exactly the same. Could you provide screenshots and example file content?

**Comment by sheerun** [comment] 2020-09-23 07:47
ping

**Comment by bignimbus** [comment] 2020-09-24 15:11
https://github.com/sheerun/vim-polyglot/commit/e166f741ef054ea990aa6d1af85b97ceb82171bb:
<img width="511" alt="Screen Shot 2020-09-24 at 11 05 50 AM" src="https://user-images.githubusercontent.com/3976692/94163777-38b12f00-fe56-11ea-9644-afa4f74bb96b.png">

`master`:
<img width="594" alt="Screen Shot 2020-09-24 at 11 03 58 AM" src="https://user-images.githubusercontent.com/3976692/94163778-3949c580-fe56-11ea-9e68-c7ac36d5fe23.png">

Content should be any component that has TSX elements in the return value.

```tsx
const MyComponent: React.FC<{}> = () => {
  return (
    <div>
      <MyHeaderComponent>
        <h1>Hello world!</h1>
      </MyHeaderComponent>
      <div>
        <p>Lorem ipsum</p>
      </div>
      <MyFooterComponent>
        &copy; 2020
      </MyFooterComponent>
    </div>
  );
};
```tsx

**Comment by sheerun** [comment] 2020-09-24 17:40
I can't reproduce. I'm using following ~/.vimrc.test:

```
runtime defaults.vim

call plug#begin()

Plug 'ayu-theme/ayu-vim'
Plug 'sheerun/vim-polyglot'

call plug#end()

colorscheme ayu
```

And following command:

```
vim -u ~/.vimrc.test foo.tsx
```


master and e166f74 look exactly the same:

https://imgur.com/a/m5zFqoh

**Comment by bignimbus** [comment] 2020-09-24 17:45
Very strange.  What is the `filetype` on your end?  Mine is `typescriptreact`.

**Comment by bignimbus** [comment] 2020-09-24 17:54
FWIW, I'm using `vim-js` and not `vim-javascript`.  Not sure if that is relevant.

**Comment by sheerun** [comment] 2020-09-24 18:32
Mine is as well `typescriptreact`. In the .vimrc above I'm not using neither vim-js or vim-javascript

**Comment by sheerun** [comment] 2020-09-25 08:54
I tried all combinations of vim-js, vim-polyglot, vim-javascript and vim-jsx-pretty, but I'm still unable to reproduce. I think the best course of action is if you push docker image on docker hub that has minimal reproduction of this issue and post another issue here. I'll close this issue for now.

**Closed by sheerun** 2020-09-25 08:54 UTC

**Comment by bignimbus** [comment] 2020-09-25 14:26
@sheerun thank you for engaging, I may do something like the above when time allows.  Have a good weekend!
