### ISSUE TITLE
Issue loading ft.vim. This error happens when I open c files.

### ISSUE THREAD

**Issue by lizardcoder9999** [sheerun/vim-polyglot#781] opened 2022-02-18 18:43 UTC
![image](https://user-images.githubusercontent.com/48844817/154743375-820d295d-66f4-469d-863b-a93a8e9e066a.png)

**Comment by delminskii** [comment] 2022-02-18 19:04
Duplicate of #779.

**Closed** 2022-02-18 19:39 UTC
