### ISSUE TITLE
E715: Dictionary Required

### ISSUE THREAD

**Issue by pvzzombs** [sheerun/vim-polyglot#632] opened 2020-11-18 09:57 UTC
I installed the vim-polyglot plugin in vim, close it, then open vim again. After opening any kind of file I an error always appear saying like this: 

```
Error detected while processing ~/.vim/bundle/vim-polyglot/syntax/cpp.vim
Line 1: E715: Dictionary required
.....
```

Is there anyway to fix this, and what should I add to my vimrc file? I already added the the varaibles g:polyglot_disabled and g:polyglot_is_disabled.

**I'm a newbie in vim, and I installed this vim-polyglot using vundle**

**Comment by sheerun** [comment] 2020-12-29 22:52
Seems like some kind of problem with loading order. Could you describe your environment, editor, version of editor, and .vimrc?

**Comment by sheerun** [comment] 2021-01-01 16:13
Probably duplicate of #613

**Closed by sheerun** 2021-01-01 16:13 UTC
Labels: Feedback required
