### ISSUE TITLE
Dockerfile syntax highlighting not working on some systems

### ISSUE THREAD

**Issue by b-ggs** [sheerun/vim-polyglot#361] opened 2019-01-03 09:49 UTC
Dockerfile syntax highlighting doesn't seem to work on my Debian 9 box

![screen shot 2019-01-03 at 5 41 36 pm 2](https://user-images.githubusercontent.com/6130147/50631370-f90a2b80-0f7e-11e9-89d1-70956e126b54.png)

To the left is my macOS Mojave terminal, and to the right is the Debian 9 VPS I'm SSH'd into.

I installed the plugin using vim-plug.

The panes are as follows:
[OS information] [Dockerfile opened in NVIM with my own NVIM configs]
[Dockerfile opened with a minimal init.vim (`nvim -u init.vim Dockerfile`)] [The init.vim used to open the file on the left]
[Latest commit of the vim-polyglot installed]

It seems that even with the minimal init.vim, my Dockerfile still isn't being highlighted on my Debian 9 box.

I have tried removing all my plugins and reinstalling them, and even upgraded my NVIM to 0.3.2 from 0.3.1 on both my Mac and my VPS, and yet for some reason on my VPS it still doesn't work.

I'm not sure what else to show you to help debug this. Please let me know what I can do to help.

**Comment by b-ggs** [comment] 2019-01-03 09:51
`:syntax` output:

* macOS Mojave
```
:syntax
--- Syntax items ---
dockerfileKeywords xxx USER SHELL RUN ADD WORKDIR ONBUILD
                   ENTRYPOINT HEALTHCHECK CMD EXPOSE MAINTAINER
                   ARG VOLUME LABEL FROM COPY AS
[...]
```

* Debian 9
```
:syntax
No Syntax items defined for this buffer
```

---

Also if it's worth mentioning, if I manually run `:set syntax=dockerfile`, the correct highlighting shows up.

**Comment by b-ggs** [comment] 2019-01-04 02:00
Moving `syntax/dockerfile.vim` to `syntax/Dockerfile.vim` seems to fix this. Will make a PR for this.

![screen shot 2019-01-04 at 9 59 08 am](https://user-images.githubusercontent.com/6130147/50670573-82654080-1007-11e9-864f-bf5b354add59.png)

**Comment by nickjj** [comment] 2019-01-20 02:35
Just popping in to say that I noticed the same exact behavior and your proposed fix worked. Thanks!

**Comment by jimmyharris** [comment] 2019-02-25 16:12
This appears to be the correct solution, I wonder if the compilation scripts need to be modified to make sure that this auto-generation works?

**Comment by jimmyharris** [comment] 2019-02-25 16:44
I created a pull request (#373) to correctly address the package naming issue at the root of the problem in the build script where it is introduced. @sheerun please spin a new build as quickly as possible.

**Comment by b-ggs** [comment] 2019-02-25 16:50
Nice, I wasn't aware of the build process and all. I'll close my PR in favor of yours. Thanks @jimmyharris!

**Comment by jimmyharris** [comment] 2019-02-25 17:07
I wonder if the issue is: @sheerun is building on MacOS. that uses a case preserving but case insensitive file system.  The automated build script wouldn't actually change the file names correctly with the current build script, and the test suite doesn't throw an error if the syntax plugin isn't actually loaded.  The spec script isn't super sophisticated in determining if the plugins did actually load. It is mostly checking for errors at load time. I'm going to close my PR because it doesn't actually fix the issue.

**Comment by jimmyharris** [comment] 2019-02-25 17:23
Sorry for the confusion. #374 is the correct fix here. It would be helpful if the build script could run on a case sensitive file system MacOS does support creating HFS+ file systems that are case sensitive see https://coderwall.com/p/mgi8ja/case-sensitive-git-in-mac-os-x-like-a-pro for an example of how to do this. Official builds of this repo probably should be conducted on Case sensitive file systems.

If you are using this on MacOS you will need to re-clone/reinstall your repo to make sure the file name change actually takes effect.

**Comment by sheerun** [comment] 2019-03-04 10:00
Hello,

Thank you for raising this issue, it was indeed because I build this plugin on MacOS. This should be now fixed on master

**Closed** 2019-03-04 10:00 UTC

**Comment by jimmyharris** [comment] 2019-03-05 16:51
thanks!
